version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DEV_DB_HOST}:5432/${DEV_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DEV_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEV_DB_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network
    depends_on:
      - postgres
      - redis

#  frontend:
#    build: ./frontend
#    container_name: frontend_app
#    ports:
#      - "80:80"
#    networks:
#      - app_network
#    depends_on:
#      - backend

volumes:
  postgres_data:

networks:
  app_network:
