services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d dev_db" ]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    networks:
      - app_network
    depends_on:
      postgres_db:
        condition: service_healthy


  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
        test: [ "CMD-SHELL", "redis-cli ping" ]
        interval: 5s
        timeout: 10s
        retries: 5

  backend:
    build: ./backend
    container_name: backend_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DEV_DB_HOST}:5432/${DEV_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DEV_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEV_DB_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    #volumes:
      #- ./backend/.env:/app/.env

#  frontend:
#    build: ./frontend
#    container_name: frontend_app
#    ports:
#      - "80:80"
#    networks:
#      - app_network
#    depends_on:
#      - backend

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
